image:
  notebook:
    image: quay.io/ml-aml-workshop/keras-tensorflow-panda-notebook:0.0.1
  postgresdb:
    image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest
  minio:
    image: docker.io/minio/minio:latest
  tensorboard:
    image: docker.io/tensorflow/tensorflow:latest-gpu

odh:
  kdef:
    version: v0.7-branch-openshift

minio:
  persistence:
    accessModes: ReadWriteOnce
    volumeSize: 5Gi

#
replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
